version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: tokumei-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  app:
    build: .
    container_name: tokumei-backend
    ports:
      - "3000:3000"
    depends_on:
      - redis
    environment:
      - NODE_ENV=development
      - REDIS_URL=redis://redis:6379
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped

volumes:
  redis_data:
