version: '3.8'

services:
  mongodb:
    image: mongo:7
    container_name: tokumei-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=tokumei_chat
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: tokumei-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  app:
    build: .
    container_name: tokumei-backend
    ports:
      - "3000:3000"
    depends_on:
      - redis
      - mongodb
    environment:
      - NODE_ENV=development
      - REDIS_URL=redis://redis:6379
      - MONGODB_URI=mongodb://mongodb:27017/tokumei_chat
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped

volumes:
  redis_data:
  mongodb_data:
